# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts_stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tts_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tts_stream.proto\x12\x06tts.v1\"\x18\n\x08TextPart\x12\x0c\n\x04text\x18\x01 \x01(\t\"n\n\nAudioChunk\x12\x11\n\tpcm_s16le\x18\x01 \x01(\x0c\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x13\n\x0bsample_rate\x18\x03 \x01(\r\x12\x10\n\x08\x63hannels\x18\x04 \x01(\r\x12\x14\n\x0c\x66irst_pcm_ms\x18\x05 \x01(\x01\x32@\n\x06Speech\x12\x36\n\nSynthesize\x12\x10.tts.v1.TextPart\x1a\x12.tts.v1.AudioChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTPART']._serialized_start=28
  _globals['_TEXTPART']._serialized_end=52
  _globals['_AUDIOCHUNK']._serialized_start=54
  _globals['_AUDIOCHUNK']._serialized_end=164
  _globals['_SPEECH']._serialized_start=166
  _globals['_SPEECH']._serialized_end=230
# @@protoc_insertion_point(module_scope)
